FROM tensorchord/vchord-suite:pg18-latest@sha256:c6e5e77a1180199f91b040b6e85c6d10b0ded6d49fb614dfd2e7272ffb91af08

COPY init.sql /docker-entrypoint-initdb.d/00-init.sql

HEALTHCHECK --interval=10s --timeout=3s --retries=10 \
    CMD pg_isready -U ${POSTGRES_USER:-arista} -d ${POSTGRES_DB:-arista}
