// <auto-generated />
using System;
using AristaMcp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace AristaMcp.Data.Migrations
{
    [DbContext(typeof(AristaDbContext))]
    [Migration("20260425121345_AddParentChunkSupport")]
    partial class AddParentChunkSupport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_tokenizer");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vchord");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vchord_bm25");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AristaMcp.Data.Entities.ChunkEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer")
                        .HasColumnName("chunk_index");

                    b.Property<string>("ChunkKind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("leaf")
                        .HasColumnName("chunk_kind");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DocumentId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("document_id");

                    b.Property<HalfVector>("Embedding")
                        .HasColumnType("halfvec(768)")
                        .HasColumnName("embedding");

                    b.Property<string>("EmbeddingModel")
                        .HasColumnType("text")
                        .HasColumnName("embedding_model");

                    b.Property<int?>("PageEnd")
                        .HasColumnType("integer")
                        .HasColumnName("page_end");

                    b.Property<int?>("PageStart")
                        .HasColumnType("integer")
                        .HasColumnName("page_start");

                    b.Property<long?>("ParentChunkId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_chunk_id");

                    b.Property<string>("RawContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_content");

                    b.Property<short?>("SectionLevel")
                        .HasColumnType("smallint")
                        .HasColumnName("section_level");

                    b.Property<string>("SectionTitle")
                        .HasColumnType("text")
                        .HasColumnName("section_title");

                    b.Property<int>("TokenCount")
                        .HasColumnType("integer")
                        .HasColumnName("token_count");

                    b.HasKey("Id");

                    b.HasIndex("ChunkKind")
                        .HasDatabaseName("idx_chunks_kind");

                    b.HasIndex("DocumentId");

                    b.HasIndex("Embedding")
                        .HasAnnotation("Npgsql:StorageParameter:ef_construction", 200)
                        .HasAnnotation("Npgsql:StorageParameter:m", 16);

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "halfvec_cosine_ops" });

                    b.HasIndex("ParentChunkId")
                        .HasDatabaseName("idx_chunks_parent_chunk_id")
                        .HasFilter("parent_chunk_id IS NOT NULL");

                    b.HasIndex("SectionLevel")
                        .HasFilter("section_level IS NOT NULL");

                    b.HasIndex("DocumentId", "ChunkIndex")
                        .IsUnique();

                    b.ToTable("chunks", t =>
                        {
                            t.HasCheckConstraint("ck_chunks_chunk_kind", "chunk_kind IN ('leaf', 'parent')");
                        });
                });

            modelBuilder.Entity("AristaMcp.Data.Entities.DocumentEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("ConvertMode")
                        .HasColumnType("text")
                        .HasColumnName("convert_mode");

                    b.Property<DateTimeOffset?>("ConvertedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("converted_at");

                    b.Property<DateTimeOffset?>("DownloadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("downloaded_at");

                    b.Property<int>("ImageCount")
                        .HasColumnType("integer")
                        .HasColumnName("image_count");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ingested_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("JsonPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("json_path");

                    b.Property<int>("Level1SectionCount")
                        .HasColumnType("integer")
                        .HasColumnName("level1_section_count");

                    b.Property<string>("MdPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("md_path");

                    b.Property<int?>("Pages")
                        .HasColumnType("integer")
                        .HasColumnName("pages");

                    b.Property<string>("PdfSha256")
                        .HasColumnType("text")
                        .HasColumnName("pdf_sha256");

                    b.Property<string>("Product")
                        .HasColumnType("text")
                        .HasColumnName("product");

                    b.Property<int>("SectionCount")
                        .HasColumnType("integer")
                        .HasColumnName("section_count");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("TagsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("tags");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("TocCount")
                        .HasColumnType("integer")
                        .HasColumnName("toc_count");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<string>("Version")
                        .HasColumnType("text")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("PdfSha256")
                        .HasDatabaseName("idx_documents_pdf_sha256");

                    b.HasIndex("Category", "Product", "Version")
                        .HasDatabaseName("idx_documents_category_product_version");

                    b.ToTable("documents");
                });

            modelBuilder.Entity("AristaMcp.Data.Entities.IngestRunEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CatalogSha256")
                        .HasColumnType("text")
                        .HasColumnName("catalog_sha256");

                    b.Property<int>("ChunksUpserted")
                        .HasColumnType("integer")
                        .HasColumnName("chunks_upserted");

                    b.Property<int>("DocsSkipped")
                        .HasColumnType("integer")
                        .HasColumnName("docs_skipped");

                    b.Property<int>("DocsTotal")
                        .HasColumnType("integer")
                        .HasColumnName("docs_total");

                    b.Property<int>("DocsUpserted")
                        .HasColumnType("integer")
                        .HasColumnName("docs_upserted");

                    b.Property<string>("ErrorMsg")
                        .HasColumnType("text")
                        .HasColumnName("error_msg");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<DateTimeOffset>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt")
                        .IsDescending();

                    b.ToTable("ingest_runs");
                });

            modelBuilder.Entity("AristaMcp.Data.Entities.ChunkEntity", b =>
                {
                    b.HasOne("AristaMcp.Data.Entities.DocumentEntity", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AristaMcp.Data.Entities.ChunkEntity", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentChunkId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Document");

                    b.Navigation("Parent");
                });
#pragma warning restore 612, 618
        }
    }
}
